module.exports = {
    MainScreen: {
        marginTop: '10%',
        display: 'flex',
        flexDirection: 'column',
        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
        height: '100%',
        // margin:'auto'
    },
    ScrollView: {
        elevation: 10,
        backgroundColor: 'white',
        width: '95%',
        height:'30%',
        borderRadius: 10,
        display: 'flex',
        // marginBottom: 10,
        padding: 10,
        // alignItem:'center',
        // justifyContent:'center'
    },
    ScrollView_Text: {
        fontSize: 50,
        textAlign: 'right',
        paddingBottom:9
    },
    keypad: {
        marginTop: '10%',
        display: 'flex',
        width: '100%',
        height: '70%',        
        justifyContent: 'top',
        // flexDirection: 'row',
        // backgroundColor: 'black',
        // justifyContent: 'space-between',
        // alignItems: 'center',
    },
    keypad_row: {
        display: 'flex',
        flexDirection: 'row',
        // backgroundColor: 'white',
        alignItems: 'center',
        width: '100%',
        // justifyContent: 'space-between',
    },
    button_outer1:{
        margin:5,
        width:80,
        height:80,
        alignItems:'center',
        justifyContent:'center',
        elevation: 10,
        backgroundColor: 'white',
        color:'red',
        overflow:'hidden',
        // margin:1,
        borderRadius:15,
    },
    button_outer2:{
        margin:5,
        width:80,
        height:80,
        alignItems:'center',
        justifyContent:'center',
        elevation: 10,
        backgroundColor: '#ff5757',
        color:'red',
        overflow:'hidden',
        // margin:1,
        borderRadius:100,
    },
    button1:{
        fontSize:30,
        backgroundColor: 'white',
        color: 'black',
    },
    button2:{
        fontSize:30,
        color: 'white',
    },
}